---
- name: Backup proxmox configuration
  hosts: proxmox

  tasks:
    - name: Backup /etv/pve/
      synchronize:
        mode: pull
        delete: yes
        src: /etc/pve/
        dest: ~/proxmox_backup/etc/pve/
