---
- name: Create self-signed certificates
  hosts: localhost
  tasks:
    - name: Create directory ./outputs
      ansible.builtin.file:
        path: ./outputs
        state: directory

    - name: Generate private key
      ansible.builtin.openssl_privatekey:
        path: "./outputs/{{ domain }}.key"
        size: 2048

    - name: Generate CSR
      ansible.builtin.openssl_csr:
        path: "./outputs/{{ domain }}.csr"
        privatekey_path: "./outputs/{{ domain }}.key"
        common_name: "{{ domain }}"
        subject_alt_name:
          - "DNS:*.{{ domain }}"
          - "IP:{{ hostvars['reverseproxy'].ansible_host }}"

    - name: Generate self-signed certificate
      ansible.builtin.openssl_certificate:
        path: "./outputs/{{ domain }}.crt"
        privatekey_path: "./outputs/{{ domain }}.key"
        csr_path: "./outputs/{{ domain }}.csr"
        provider: selfsigned
        selfsigned_not_after: +3650d

    - name: Encrypt certificate
      include_role:
        name: encrypt_string
      vars:
        name: ssl_certificate
        string: "{{ lookup('ansible.builtin.file', './outputs/' + domain + '.crt') }}"

    - name: Encrypt private key
      include_role:
        name: encrypt_string
      vars:
        name: ssl_certificate_key
        string: "{{ lookup('ansible.builtin.file', './outputs/' + domain + '.key') }}"
