---
- import_playbook: detect_ssh_port.yaml
- import_playbook: initial_host_setup.yaml
- import_playbook: reverseproxy.yaml
- import_playbook: pihole.yaml
- import_playbook: nextcloud.yaml
- import_playbook: gitlab.yaml
- import_playbook: navidrome.yaml
- import_playbook: yourspotify.yaml
- import_playbook: wireguard.yaml
