---
version: '3'

vars:
  VAULT_PASS_FILE: ".vault-pass"

tasks:
  site-multipass:
    desc: Run site.yaml against multipass
    cmds:
      - ansible-playbook --vault-pass-file {{.VAULT_PASS_FILE}} -i inventory/multipass.yaml playbooks/site.yaml
    silent: true
