---
version: '3'

vars:
  MULTIPASS_DOMAIN: "multipass.local"
  VAULT_PASS_FILE: ".vault-pass"

tasks:
  default:
    desc: Launch and set up multipass environment
    aliases: [multipass]
    cmds:
      - task: multipass-launch
      - task: multipass-site
      - task: multipass-certificate
    silent: true

  multipass-launch:
    desc: Launch multipass VMs
    cmds: [./multipass/launch.sh]
    silent: true

  multipass-site:
    desc: Run site.yaml against multipass
    cmds:
      - ansible-playbook --vault-pass-file {{.VAULT_PASS_FILE}} -i inventory/multipass.yaml playbooks/site.yaml
    silent: true

  multipass-certificate:
    desc: Import (and overwrite if necessary) multipass (traefik) certificate
    cmds:
      - sudo true
      - sed -i '/^10\.10\.0\.1/d' ~/.ssh/known_hosts
      - "scp -o StrictHostKeyChecking=accept-new multipass-control:~/traefik-certs/{{.MULTIPASS_DOMAIN}}.crt ./"
      - sudo mv -f ./{{.MULTIPASS_DOMAIN}}.crt /etc/pki/ca-trust/source/anchors/
      - sudo update-ca-trust
    silent: true

  multipass-delete:
    desc: Delete multipass VMs
    cmds:
      - multipass stop --force control
      - multipass stop --force worker1
      - multipass stop --force worker2
      - multipass delete control
      - multipass delete worker1
      - multipass delete worker2
      - multipass purge
      - nmcli connection delete multipassbr
    silent: true
