---
- name: Encrypt string
  ansible.builtin.shell: ansible-vault encrypt_string --vault-pass-file .vault-pass '{{ string }}' --name {{ name }}
  register: encrypted_string
  no_log: true

- name: Write the encrypted string to YAML file
  ansible.builtin.copy:
    content: "{{ encrypted_string.stdout }}"
    dest: "./outputs/{{ name }}.yaml"
    mode: "644"
