---
all:
  children:
    docker_host:
      hosts:
        pihole:
          ansible_host: 192.168.1.1
          ansible_user: user
        reverseproxy:
          ansible_host: 192.168.1.2
          ansible_user: user
        wireguard:
          ansible_host: 192.168.1.3
          ansible_user: user
        nextcloud:
          ansible_host: 192.168.1.4
          ansible_user: user
        gitea:
          ansible_host: 192.168.1.5
          ansible_user: user
        navidrome:
          ansible_host: 192.168.1.6
          ansible_user: user
        yourspotify:
          ansible_host: 192.168.1.7
          ansible_user: user
