---
all:
  children:
    docker_host:
      hosts:
        pihole:
          ansible_host: 192.168.0.200
          ansible_user: user
        nextcloud:
          ansible_host: 192.168.0.201
          ansible_user: user
        gitlab:
          ansible_host: 192.168.0.202
          ansible_user: user
        your_spotify:
          ansible_host: 192.168.0.203
          ansible_user: user
