---
# When using this role be sure to set 'gather_facts' to 'no'

- name: Test SSH port {{ sshd_port }}
  local_action: wait_for port={{ sshd_port }} timeout=5 host={{ ansible_host }}
  register: port_test
  ignore_errors: yes

- name: Set ansible_ssh_port
  set_fact:
    ansible_ssh_port: "{% if port_test.elapsed < 5 %}{{ sshd_port }}{% else %}22{% endif %}"

- name: Update sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: "Port {{ sshd_port }}"
  become: yes
  notify: Restart sshd

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: Gather facts
  ansible.builtin.setup:
  register: gathered_facts
