---
- name: Update sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: "Port {{ sshd_port }}"
  become: true
  notify: Restart sshd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Gather facts
  ansible.builtin.setup:
  register: gathered_facts
