---
- name: Create nginx directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/nginx"
    state: directory
    mode: "755"

- name: Copy nginx configuration files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/nginx/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: "644"
  with_fileglob:
    - "templates/nginx/*.conf.j2"
  notify: Restart docker compose

- name: Create certs directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/nginx/certs"
    state: directory
    mode: "755"

- name: Copy SSL certificate
  ansible.builtin.copy:
    content: "{{ ssl_certificate }}"
    dest: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/nginx/certs/{{ domain }}.crt"
    mode: "644"
  notify: Restart docker compose

- name: Copy SSL certificate key
  ansible.builtin.copy:
    content: "{{ ssl_certificate_key }}"
    dest: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/nginx/certs/{{ domain }}.key"
    mode: "644"
  notify: Restart docker compose

- name: Copy compose.yaml
  ansible.builtin.copy:
    src: compose.yaml
    dest: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/compose.yaml"
    mode: "644"
  notify: Restart docker compose
