---
- name: Ensure directory {{ ansible_env.HOME }}/your_spotify exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/your_spotify"
    state: directory

- name: Copy compose.yaml
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ ansible_env.HOME }}/your_spotify/compose.yaml"

- name: Ensure docker compose is up and running
  community.docker.docker_compose:
    project_src: "{{ ansible_env.HOME }}/your_spotify"
