---
- name: Remove default .zshrc
  file:
    state: absent
    path: ~/.zshrc

- name: Create symbolic link for .zshrc
  file:
    src: ~/.dotfiles/zsh/.zshrc
    dest: ~/.zshrc
    state: link

- name: Create symbolic link for .tmux.conf
  file:
    src: ~/.dotfiles/tmux/.tmux.conf
    dest: ~/.tmux.conf
    state: link
