---
- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Set zsh as default shell
  shell: chsh -s /bin/zsh

- name: Install oh-my-zsh
  shell: yes Yes | sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: Install Neovim 0.7.0
  block:
    - name: "Check if Neovim is installed"
      package_facts:
        manager: "auto"

    - name: Download nvim-linux64.deb
      get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb
        dest: /tmp/nvim-linux64.deb
      when: "'neovim' not in ansible_facts.packages"

    - name: Install nvim-linux64.deb
      apt:
        deb: /tmp/nvim-linux64.deb
      when: "'neovim' not in ansible_facts.packages"

    - name: Delete nvim-linux64.deb
      file:
        state: absent
        path: /tmp/nvim-linux64.deb
      when: "'neovim' not in ansible_facts.packages"
    
    - name: Install packer.nvim
      git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

- name: Install tmux
  apt:
    name: tmux
    state: present
