---
- name: Install zsh
  apt:
    name: zsh
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Set zsh as default shell
  shell: chsh -s /bin/zsh

- name: Install Vim
  apt:
    name: vim
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Install Git
  apt:
    name: git
    state: present

- name: Install htop
  apt:
    name: htop
    state: present

- name: Install tmux
  apt:
    name: tmux
    state: present
