---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
  notify:
    - Reset connection
    - Set ansible_ssh_port

- name: Reset connection
  ansible.builtin.meta: reset_connection

- name: Set ansible_ssh_port
  ansible.builtin.set_fact:
    ansible_ssh_port: "{{ sshd_port }}"
  run_once: true
