" Vundle                                                                                                                                                                                          
set nocompatible
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
 Plugin 'VundleVim/Vundle.vim'
 Plugin 'joshdick/onedark.vim'
 Plugin 'sheerun/vim-polyglot'
 Plugin 'vim-airline/vim-airline'
call vundle#end()
filetype plugin indent on

" Visuals
syntax on
silent! colorscheme onedark
set number
set cursorline
set nowrap

" Search settings
set ignorecase
set hlsearch
set incsearch

" Key mappings
nnoremap <esc><esc> :silent! nohls<cr>
