" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'joshdick/onedark.vim'
Plugin 'preservim/nerdtree'
Plugin 'sheerun/vim-polyglot'
Plugin 'vim-airline/vim-airline'
call vundle#end()
filetype plugin indent on

" Other settings
syntax on
silent! colorscheme onedark
set number
nmap _ :NERDTreeToggle<CR>
