---
- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/pihole"
    state: directory
    mode: "755"
  become: true

- name: Create directory /etc/systemd/resolved.conf.d
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: "755"
  become: true

- name: Disable DNSStubListener in systemd-resolved
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/10-make-dns-work.conf
    content: |
      [Resolve]
      DNSStubListener=no
    owner: root
    group: root
    mode: "644"
  become: true
  notify: Restart services

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Copy custom.list
  ansible.builtin.template:
    src: custom.list.j2
    dest: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/pihole/custom.list"
    mode: "644"
  become: true
  notify: Restart docker compose

- name: Copy compose.yaml
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/compose.yaml"
    mode: "644"
  notify: Restart docker compose
