---
- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/pihole"
    state: directory
    mode: "755"

- name: Create directory /etc/systemd/resolved.conf.d
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: "755"
  become: true

- name: Disable DNSStubListener in systemd-resolved
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/10-make-dns-work.conf
    content: |
      [Resolve]
      DNSStubListener=no
    owner: root
    group: root
    mode: "644"
  become: true
  register: systemd_resolved

- name: Restart systemd-resolved to apply changes
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
  become: true
  when: systemd_resolved.changed

- name: Restart docker to apply changes
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  become: true
  when: systemd_resolved.changed

- name: Copy custom.list
  ansible.builtin.template:
    src: custom.list.j2
    dest: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/pihole/custom.list"
  become: true

- name: Copy compose.yaml
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ ansible_env.HOME }}/{{ inventory_hostname }}/compose.yaml"

- name: Ensure docker compose is up and running
  community.docker.docker_compose:
    project_src: "{{ ansible_env.HOME }}/{{ inventory_hostname }}"
